export default {
  CARD_LIST_UPDATED: 'CARD_LIST_UPDATED',

  CARD_PROXIES_REQUESTED: 'CARD_PROXIES_REQUESTED',
  CARD_PROXIES_SUCCEEDED: 'CARD_PROXIES_SUCCEEDED',
  CARD_PROXIES_FAILED: 'CARD_PROXIES_FAILED',

  DECK_LIST_UPDATED: 'DECK_LIST_UPDATED',

  DECK_MARKERS_REQUESTED: 'DECK_MARKERS_REQUESTED',
  DECK_MARKERS_SUCCEEDED: 'DECK_MARKERS_SUCCEEDED',
  DECK_MARKERS_FAILED: 'DECK_MARKERS_FAILED',
}